version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - env    
      -  sh install.sh
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket ${ARTIFACT_BUCKET} --output-template-file outputtemplate.yaml --debug
artifacts:
  files:
    - outputtemplate.yaml     